##################################################
# Kuwo 音乐 for Quantumult X
##################################################

[rewrite_local]
# 统一扩大匹配（更容易命中）
^https?:\/\/.*kuwo\.cn\/.* url script-response-body https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/kuwo.js

[mitm]
hostname = *.kuwo.cn
