##################################################
# Kuwo 音乐 for Quantumult X
##################################################
# 统一扩大匹配（更容易命中）
^https?:\/\/.*kuwo\.cn\/(vip|music|api)\/.* url script-response-body https://cdn.jsdelivr.net/gh/Yuheng0101/X/Scripts/kuwo.js

hostname = *.kuwo.cn, ad.tencentmusic.com, abt-kuwo.tencentmusic.com
